#!/usr/bin/perl
#
# Download and install Alien Arena maps
#


my $DOWNLOADCOMMAND = "/usr/bin/wget";
my $ZIPLISTCMD = "/usr/bin/unzip -l";
my $ZIPEXTRACTCMD = "/usr/bin/unzip";
my $HOMEDIR = $ENV{HOME};
my $PREFFILE = "$HOMEDIR/.addmaprc";
my $MAP_PATH = "";

# No changes below here

my $VERSION = "0.1";
my $NumArgs = $#ARGV + 1;
my @MapNames = ();

print "addmap v$VERSION\n";
print "=============\n";
if ($NumArgs != 1)
{
	print "Usage:\n addmap \<URL TO MAP\>\n";
	exit 0;
}
my $MapUrl = $ARGV[0];
print "Map URL: $MapUrl\n";

if (substr($MapUrl, 0, 4) ne "http")
{
	print "$MapUrl doesn't seem to be a URL\n";
	exit 0;
}

if (! -f $PREFFILE)
{
	print "Prefs not found, creating.\n";
	print "What is the path to the Alien Arena folder: ";
	$MAP_PATH = <stdin>;
	chop($MAP_PATH);
	print "Map Path = '$MAP_PATH'\n";
	open(my $FH, '>', $PREFFILE) or die "Could not create file '$PREFFILE' $!";
	print $FH "$MAP_PATH\n";
	close ($FH);
}
else
{
        open(my $FH, '<', $PREFFILE) or die "Could not open file '$PREFFILE' $!";
	while (<$FH>)
	{
		chop();
		$MAP_PATH = $_;
	}
        print "Map Path = $MAP_PATH\n";
        close ($FH);
}

if (substr($MapUrl, -4) ne ".zip")
{
	print "That file doesn't seem to be a zip file: $MapUrl\n";
	exit 0;
}

# Change to alien arena folder
chdir($MAP_PATH);

# Download the map file
system("$DOWNLOADCOMMAND \"$MapUrl\"");
# Get the standalone zip file
my $SlashPos = rindex($MapUrl, "/") + 1;
my $MapFile = substr($MapUrl, $SlashPos);
print "MapFile = $MapFile\n";

my $NumMaps = 0;
my @ziplistlines = `$ZIPLISTCMD $MapFile | grep arena/maps | grep \.bsp`;
while(@ziplistlines)
{
	my $FileLine = shift @ziplistlines;
	chop($FileLine);
	#print "Saw line '$FileLine'\n";
	$SlashPos = rindex($FileLine, "/") + 1;
	my $MapName = substr($FileLine, $SlashPos);
	print "Saw Map Name: $MapName\n";
	push(@MapNames, $MapName);
	$NumMaps++;
}
print "Saw $NumMaps maps in archive\n";

if ($NumMaps == 0)
{
	print "No maps found in archive - aborting\n";
	exit 0;
}
# Extract the files
system("$ZIPEXTRACTCMD $MapFile");
print "Maps Extracted\n";
exit 0;
